import type {
  Asset,
  Character,
  GenerationJob,
  Project,
  Script,
  Segment,
  Shot,
  SourceDocument,
} from "@/lib/schemas";

const now = "2026-07-05T09:00:00.000+08:00";

export const projects: Project[] = [
  {
    id: "project-aurora",
    name: "月光檔案：失落列車",
    description: "把長篇懸疑故事拆成 9:16 Shorts 系列，自動產出分鏡、角色一致性提示與影片任務。",
    type: "shorts",
    defaultAspectRatio: "9:16",
    defaultLanguage: "bilingual",
    defaultStyle: "cinematic noir, teal highlights, realistic faces",
    defaultSegmentCount: 6,
    defaultImageModel: "mock-image-cinematic-v1",
    defaultVideoModel: "mock-image-to-video-v1",
    costLimit: 80,
    status: "storyboard_ready",
    createdAt: "2026-07-01T10:20:00.000+08:00",
    updatedAt: now,
  },
  {
    id: "project-course",
    name: "AI 課程宣傳短片",
    description: "課程銷售頁故事化影片，包含 SEO 標題、旁白、分鏡與匯出包。",
    type: "course",
    defaultAspectRatio: "16:9",
    defaultLanguage: "zh",
    defaultStyle: "bright SaaS explainer, clean product visuals",
    defaultSegmentCount: 4,
    defaultImageModel: "mock-image-cinematic-v1",
    defaultVideoModel: "mock-text-to-video-v1",
    costLimit: 120,
    status: "text_ready",
    createdAt: "2026-06-28T16:00:00.000+08:00",
    updatedAt: "2026-07-03T11:15:00.000+08:00",
  },
];

export const sourceDocuments: SourceDocument[] = [
  {
    id: "source-001",
    projectId: "project-aurora",
    filename: "moonlight-train.md",
    fileType: "md",
    rawText: "女主角在午夜月台收到不存在班次的車票...",
    parsedText:
      "主角林雨晴在午夜月台追查失蹤父親，發現列車會停靠被記憶抹除的城市。",
    status: "parsed",
    createdAt: "2026-07-01T10:30:00.000+08:00",
  },
];

export const segments: Segment[] = [
  {
    id: "segment-001",
    projectId: "project-aurora",
    order: 1,
    titleZh: "午夜月台",
    titleEn: "The Midnight Platform",
    summaryZh: "林雨晴在空無一人的月台收到父親筆跡的車票。",
    summaryEn: "Yuqing receives a ticket written in her missing father's hand.",
    storyPurpose: "建立懸疑鉤子與主角動機。",
    emotion: "uneasy, curious",
    location: "old train station",
    characters: ["character-yuqing"],
    estimatedShots: 4,
    userShotCount: 4,
    approved: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "segment-002",
    projectId: "project-aurora",
    order: 2,
    titleZh: "不存在的列車",
    titleEn: "The Train That Should Not Exist",
    summaryZh: "列車無聲進站，車窗倒映出十年前的城市。",
    summaryEn: "A silent train arrives, reflecting a city from ten years ago.",
    storyPurpose: "把超自然規則具象化。",
    emotion: "awe, dread",
    location: "platform and train interior",
    characters: ["character-yuqing", "character-conductor"],
    estimatedShots: 5,
    userShotCount: 5,
    approved: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const scripts: Script[] = [
  {
    id: "script-001",
    projectId: "project-aurora",
    segmentId: "segment-001",
    narrationZh:
      "午夜十二點，林雨晴站在被霧氣吞沒的月台。廣播沒有聲音，只有一張車票滑到她腳邊。",
    narrationEn:
      "At midnight, Yuqing stands on a fog-swallowed platform. The speakers are silent. A ticket slides to her feet.",
    characterAction: "Yuqing kneels, picks up the ticket, and recognizes her father's handwriting.",
    emotionalDirection: "quiet tension, restrained fear",
    visualDirection: "wide empty platform, mist, fluorescent flicker, close-up on the ticket",
    suggestedShotCount: 4,
    userShotCount: 4,
    difficulty: "medium",
    generationRisk: "Low risk; needs consistent ticket prop and station lighting.",
    approved: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const shots: Shot[] = [
  {
    id: "shot-001",
    projectId: "project-aurora",
    segmentId: "segment-001",
    order: 1,
    titleZh: "空月台全景",
    titleEn: "Empty Platform Wide Shot",
    plotZh: "林雨晴站在濃霧中的老月台，遠處時鐘停在 00:00。",
    plotEn: "Yuqing stands on an old foggy platform. The clock reads 00:00.",
    characters: ["character-yuqing"],
    location: "old train station platform",
    timeOfDay: "midnight",
    emotion: "uneasy",
    camera: "wide shot, low angle",
    movement: "slow dolly in",
    imagePromptZh:
      "電影感寫實風格，午夜老車站月台，濃霧，年輕女性背影，時鐘停在 00:00，藍綠冷光。",
    imagePromptEn:
      "Cinematic realistic old train station platform at midnight, dense fog, young woman from behind, clock at 00:00, teal cold light.",
    videoPromptZh: "鏡頭緩慢推近女主角，霧氣流動，燈管微微閃爍。",
    videoPromptEn:
      "Slow dolly toward the heroine, drifting fog, subtle fluorescent flicker.",
    negativePrompt: "extra limbs, distorted face, unreadable clock, watermark",
    continuityRules:
      "Yuqing wears a beige trench coat, shoulder-length black hair, small silver necklace.",
    aspectRatio: "9:16",
    imageModel: "mock-image-cinematic-v1",
    videoModel: "mock-image-to-video-v1",
    imageStatus: "approved",
    videoStatus: "queued",
    approvedImageAssetId: "asset-image-001",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shot-002",
    projectId: "project-aurora",
    segmentId: "segment-001",
    order: 2,
    titleZh: "車票滑入畫面",
    titleEn: "Ticket Slides Into Frame",
    plotZh: "泛黃車票從黑暗處滑到她腳邊，票面寫著父親的名字。",
    plotEn: "A yellowed ticket slides from the dark, bearing her father's name.",
    characters: ["character-yuqing"],
    location: "platform floor",
    timeOfDay: "midnight",
    emotion: "shock",
    camera: "close-up",
    movement: "subtle handheld drift",
    imagePromptZh:
      "老月台地面特寫，泛黃車票滑到黑色皮鞋旁，冷色霧氣，電影級景深。",
    imagePromptEn:
      "Close-up on old platform floor, yellowed train ticket beside black shoes, cold fog, cinematic depth of field.",
    videoPromptZh: "車票輕輕滑入畫面並停下，女主角的手遲疑伸向它。",
    videoPromptEn:
      "The ticket slides into frame and stops; the heroine's hand hesitates before reaching.",
    negativePrompt: "wrong text, modern station, cartoon, watermark",
    continuityRules:
      "Ticket is aged ivory paper, dark blue ink, same prop in later shots.",
    aspectRatio: "9:16",
    imageModel: "mock-image-cinematic-v1",
    videoModel: "mock-image-to-video-v1",
    imageStatus: "success",
    videoStatus: "pending",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shot-003",
    projectId: "project-aurora",
    segmentId: "segment-002",
    order: 1,
    titleZh: "無聲列車進站",
    titleEn: "Silent Train Arrival",
    plotZh: "沒有引擎聲的銀色列車從霧中浮現，車窗像黑色鏡面。",
    plotEn: "A silent silver train emerges from fog, windows like black mirrors.",
    characters: ["character-yuqing", "character-conductor"],
    location: "station track",
    timeOfDay: "midnight",
    emotion: "dread",
    camera: "telephoto compression",
    movement: "train glides forward",
    imagePromptZh:
      "銀色復古列車從濃霧中出現，黑色鏡面車窗，老月台，超現實電影感。",
    imagePromptEn:
      "Retro silver train emerging from dense fog, black mirror windows, old platform, surreal cinematic realism.",
    videoPromptZh: "列車無聲滑入月台，霧氣被車頭推開，女主角後退半步。",
    videoPromptEn:
      "The train glides silently into the platform, fog parting around the nose as Yuqing steps back.",
    negativePrompt: "modern bullet train, crowd, bright daylight, watermark",
    continuityRules:
      "Train has no visible logo; conductor appears as a distant silhouette only.",
    aspectRatio: "9:16",
    imageModel: "mock-image-cinematic-v1",
    videoModel: "mock-image-to-video-v1",
    imageStatus: "queued",
    videoStatus: "pending",
    createdAt: now,
    updatedAt: now,
  },
];

export const characters: Character[] = [
  {
    id: "character-yuqing",
    projectId: "project-aurora",
    nameZh: "林雨晴",
    nameEn: "Lin Yuqing",
    gender: "female",
    ageRange: "26-30",
    bodyType: "slim, average height",
    faceFeatures: "oval face, tired eyes, natural eyebrows",
    hairFeatures: "shoulder-length black hair, slightly messy from rain",
    outfitFeatures: "beige trench coat, dark turtleneck, black ankle boots",
    colorPalette: "beige, charcoal, muted teal",
    personality: "careful, stubborn, haunted by unanswered family history",
    fixedPromptZh:
      "26 歲亞洲女性，橢圓臉，肩長黑髮，米色風衣，深色高領，疲憊但堅定的眼神。",
    fixedPromptEn:
      "26-year-old Asian woman, oval face, shoulder-length black hair, beige trench coat, dark turtleneck, tired but determined eyes.",
    negativePrompt: "different coat color, blonde hair, heavy makeup, smiling",
    lockedReferenceAssetId: "asset-ref-yuqing",
    consistencyNotes: "Always keep the silver necklace and beige trench coat visible when possible.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "character-conductor",
    projectId: "project-aurora",
    nameZh: "列車長",
    nameEn: "The Conductor",
    gender: "male",
    ageRange: "unknown",
    bodyType: "tall, narrow shoulders",
    faceFeatures: "mostly hidden under cap shadow",
    hairFeatures: "not visible",
    outfitFeatures: "old navy conductor uniform, white gloves",
    colorPalette: "navy, brass, off-white",
    personality: "polite, unnervingly calm, speaks as if time is optional",
    fixedPromptZh: "高瘦男性列車長，深藍復古制服，白手套，帽沿遮住臉。",
    fixedPromptEn:
      "Tall slim male train conductor, old navy uniform, white gloves, face hidden by cap shadow.",
    negativePrompt: "friendly smile, modern uniform, visible full face",
    consistencyNotes: "Keep face obscured until the reveal segment.",
    createdAt: now,
    updatedAt: now,
  },
];

export const assets: Asset[] = [
  {
    id: "asset-image-001",
    projectId: "project-aurora",
    shotId: "shot-001",
    type: "generated_image",
    url: "/mock/shot-001-v1.jpg",
    localPath: "storage/assets/project-aurora/shot-001-v1.jpg",
    filename: "shot-001-v1.jpg",
    version: 1,
    provider: "mock",
    model: "mock-image-cinematic-v1",
    promptSnapshot: shots[0].imagePromptEn,
    cost: 0,
    status: "approved",
    createdAt: now,
  },
  {
    id: "asset-ref-yuqing",
    projectId: "project-aurora",
    characterId: "character-yuqing",
    type: "reference_image",
    url: "/mock/yuqing-reference.jpg",
    localPath: "storage/assets/project-aurora/yuqing-reference.jpg",
    filename: "yuqing-reference.jpg",
    version: 1,
    provider: "mock",
    model: "mock-image-cinematic-v1",
    promptSnapshot: characters[0].fixedPromptEn,
    cost: 0,
    status: "approved",
    createdAt: now,
  },
];

export const generationJobs: GenerationJob[] = [
  {
    id: "job-001",
    projectId: "project-aurora",
    shotId: "shot-001",
    type: "image",
    provider: "mock",
    model: "mock-image-cinematic-v1",
    mode: "image",
    status: "success",
    inputPayload: { prompt: shots[0].imagePromptEn, aspectRatio: "9:16" },
    outputPayload: { assetId: "asset-image-001", version: 1 },
    inputAssets: [],
    outputAssetId: "asset-image-001",
    estimatedCost: 0,
    actualCost: 0,
    retryCount: 0,
    createdAt: "2026-07-05T08:50:00.000+08:00",
    startedAt: "2026-07-05T08:50:03.000+08:00",
    completedAt: "2026-07-05T08:50:12.000+08:00",
  },
  {
    id: "job-002",
    projectId: "project-aurora",
    shotId: "shot-001",
    type: "video",
    provider: "mock",
    model: "mock-image-to-video-v1",
    mode: "image_to_video",
    status: "queued",
    inputPayload: { prompt: shots[0].videoPromptEn, inputAssetId: "asset-image-001" },
    inputAssets: ["asset-image-001"],
    estimatedCost: 0,
    retryCount: 0,
    createdAt: now,
  },
  {
    id: "job-003",
    projectId: "project-aurora",
    type: "export",
    provider: "mock",
    model: "local-export-packager",
    mode: "zip",
    status: "pending",
    inputPayload: { formats: ["xlsx", "pdf", "docx", "zip"] },
    inputAssets: ["asset-image-001"],
    estimatedCost: 0,
    retryCount: 0,
    createdAt: now,
  },
];

export function getProject(projectId: string) {
  return projects.find((project) => project.id === projectId) ?? projects[0];
}

export function getProjectBundle(projectId: string) {
  const project = getProject(projectId);
  return {
    project,
    sourceDocuments: sourceDocuments.filter((item) => item.projectId === project.id),
    segments: segments.filter((item) => item.projectId === project.id),
    scripts: scripts.filter((item) => item.projectId === project.id),
    shots: shots.filter((item) => item.projectId === project.id),
    characters: characters.filter((item) => item.projectId === project.id),
    assets: assets.filter((item) => item.projectId === project.id),
    generationJobs: generationJobs.filter((item) => item.projectId === project.id),
  };
}
